### ISSUE TITLE
tagfastq: cannot allocate memory

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#133]
# Problem

I'm trying to run library with 440 M read pairs and I'm getting a traceback due to being unable to allocate memory in the `tagfastq` step (see log file at the bottom).

Since Cutadapt works fine with the given amount of reads I'm a bit confused as to what might be giving this error, are we misusing `dnaio` or could this be because we've already allocated a lot of memory to holding the barcoding information?

If I remember correctly `cutadapt` threads by assigning a specific core for reading, could this be related since the traceback specifies it **cannot allocate** memory (rather than running out of it).

I'm running the pipe with 20 cores, 128 Gb RAM.

### Barcode reading functions
```
def parse_corrected_barcodes(open_file):
    """
    Parse starcode cluster output and return a dictionary with raw sequences pointing to a
    corrected canonical sequence
    :param open_file: starcode tabular output file.
    :return: dict: raw sequences pointing to a corrected canonical sequence.
    """
    corrected_barcodes = dict()
    for cluster in tqdm(open_file, desc="Clusters processed"):
        canonical_seq, _, cluster_seqs = cluster.strip().split("\t", maxsplit=3)
        corrected_barcodes.update({raw_seq: canonical_seq for raw_seq in cluster_seqs.split(",")})
    return corrected_barcodes
```
```
def parse_raw_barcodes(open_file):
    """
    Parse FASTA/FASTQ containing barcode sequences and return a dictionary with entry headers
    pointing to a raw barcodes sequence.
    :param open_file: dnaio odject.
    :return: dict: entry headers pointing to a raw barcodes sequence
    """
    raw_barcodes = dict()
    for barcode in tqdm(open_file, desc="Raw barcodes processed"):
        header, _ = barcode.name.split(maxsplit=1)
        raw_barcodes[header] = barcode.sequence
    return raw_barcodes
```
### Loop at traceback

```
 with dnaio.open(args.input1, file2=args.input2, interleaved=in_interleaved, mode="r") as reader, \
            dnaio.open(args.output1, file2=args.output2, interleaved=out_interleaved, mode="w") as writer:
        for read1, read2 in tqdm(reader, desc="Read pairs processed"):
            # Header parsing
            name_and_pos_r1, read_and_index_r1 = read1.name.split(maxsplit=1)
            name_and_pos_r2, read_and_index_r2 = read2.name.split(maxsplit=1)

            try:
                raw_barcode_seq = raw_barcodes[name_and_pos_r1]
            except KeyError:
                raw_barcode_seq = None
                reads_missing_barcode += 1

            if raw_barcode_seq:
                corr_barcode_seq = corrected_barcodes[raw_barcode_seq]

                raw_barcode_id = f"{args.sequence_tag}:Z:{raw_barcode_seq}"
                corr_barcode_id = f"{args.barcode_tag}:Z:{corr_barcode_seq}"

                # Create new name with barcode information.
                new_name = separator.join([name_and_pos_r1, raw_barcode_id, corr_barcode_id])

                # Save header to read instances
                read1.name = " ".join([new_name, read_and_index_r1])
                read2.name = " ".join([new_name, read_and_index_r2])

            # Write to out
            writer.write(read1, read2)
```
## Log file

```
SETTINGS FOR: tagfastq raw_barcodes: barcodes.fasta
 corrected_barcodes: barcodes.clstr
 input1: trimmed.1.fastq.gz
 input2: trimmed.2.fastq.gz
 output1: trimmed_barcoded.1.fastq.gz
 output2: trimmed_barcoded.2.fastq.gz
 barcode_tag: BX
 sequence_tag: RX
 sep: _
tagfastq - INFO: Starting
Clusters processed: 7774460it [00:21, 362636.59it/s]
Raw barcodes processed: 433169093it [27:54, 258621.92it/s]
tagfastq - INFO: Input detected as paired FASTQ.
tagfastq - INFO: Output detected as paired FASTQ.
Traceback (most recent call last):
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/bin/blr", line 11, in <module>
    load_entry_point('blr', 'console_scripts', 'blr')()
  File "/crex/proj/uppstore2018173/private/scripts/BLR/src/blr/__main__.py", line 45, in main
    module.main(args)
  File "/crex/proj/uppstore2018173/private/scripts/BLR/src/blr/cli/tagfastq.py", line 57, in main
    with dnaio.open(args.input1, file2=args.input2, interleaved=in_interleaved, mode="r") as reader, \
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/dnaio/__init__.py", line 83, in open
    return PairedSequenceReader(file1, file2, fileformat)
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/dnaio/__init__.py", line 225, in __init__
    self.reader1 = stack.enter_context(_open_single(file1, fileformat=fileformat))
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/dnaio/__init__.py", line 130, in _open_single
    file = xopen(path, mode + 'b')
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/xopen/__init__.py", line 404, in xopen
    return _open_gz(filename, mode, compresslevel, threads)
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/xopen/__init__.py", line 353, in _open_gz
    return open_with_threads()
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/xopen/__init__.py", line 339, in open_with_threads
    return PipedGzipReader(filename, mode, threads=threads)
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/site-packages/xopen/__init__.py", line 218, in __init__
    self.process = Popen(pigz_args, stdout=PIPE, stderr=PIPE)
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/proj/uppstore2018173/private/external/nbis-meta/envs/blr-master/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by FrickTobias** [comment]
@marcelm Do you have any insight to `dnaio`? Or do you think it might be related to something else?

**Comment by marcelm** [comment]
The problem when dnaio calls into xopen, which tries to open a subprocess for reading the input gzip file. None of these use large amounts of memory, so possibly some other process is running at the same time, eating up all the memory, so that nothing is left for tagfastq.

But I’ll take a closer look.

**Comment by marcelm** [comment]
The problem is that tagfastq reads the entire `barcodes.fasta` file into memory, which is huge (36 GB on my dataset). Since the input reads (in `trimmed.[12].fastq.gz`) are in the same order as in `barcodes.fasta`, it’s not actually necessary to do this. I think you should therefore focus on changing the algorithm. Let me know if you need help.

**Comment by marcelm** [comment]
I had an idea I want to mention: I would suggest to change the barcodes.fasta file in such a way that it includes *all* the reads. That is, use no filtering options in Cutadapt. Then one can iterate over the `barcodes.fasta` file and the input reads simultaneously (similar to how one would merge two sorted lists). Then I would change it so that tagfastq does not read the `barcodes.fasta` file from disk, but from stdin, and then the Cutadapt output can be piped directly into it, and no huge intermediate file needs to be created.

**Comment by pontushojer** [comment]
I did some modifications to the tagfastq script so that it reads the barcodes.fasta in parallel to the reads an implemented a buffering/cache system to catch any missing reads or barcode entries. Comparing for FASTQs with 1 million reads the improvement was quite big. 

Parameter | Old script | New script |
--- | ---: | ---:
User time (seconds) | 158.88 | 160.43
System time (seconds | 9.54 | 3.34
Percent of CPU this job got |  182% | 300%
Elapsed (wall clock) time (h:mm:ss or m:ss) | 1:32.07 | 0:54.50
Maximum resident set size (kbytes) | 271,344 | 168,844

The updated script an be found in the [tagfastq-improvement branch](https://github.com/FrickTobias/BLR/tree/tagfastq-improvement). 

This way we don't need to change any other parts of the pipe. 

If we were to keep all the entries in the barcode.fasta then this would include untrimmed reads in the clustering. Then we would need to implement a catch system for removing these as legit barcodes. 

Also is it really possible to avoid writing the barcodes to disc? We need the file both for the starcode clustering and the tagging of the reads FASTQs. We would need to split the pipe from extracting the barcodes.fasta to both `tagfastq` and `starcode` and then wait until starcode finished before starting `tagfastq`. Is this really possible or is there an other solution that I am missing?

**Comment by marcelm** [comment]
I overlooked that starcode also needs the `barcodes.fasta` file. So that needs to exist on disk. I think what would work is to pipe the output of the other Cutadapt process (that removes barcodes and adapters) into tagfastq instead. That would allow us to skip the `trimmed.[12].fastq.gz` file and go directly to `trimmed_barcoded.[12].fastq.gz`. But that should be done as a separate improvement later.

By the way, if I understand correctly that you only keep the last ten records from `barcodes.fasta` in memory, then the memory usage should go down a lot more on bigger datasets than what your table above implies.

**Comment by pontushojer** [comment]
Yes piping from the read trimming step is a possibility! 

So the new script is build to handle either missing barcode entries or missing read entries. For each read header we want to find the corresponding header in the barcode file. For this I have made a cache that stores barcodes (`headers: barcode_seq` pairs) that don't match the current read header and a function that searches the cache and reads the barcode file. The function will move forward up to 10 positions in the barcode file to look for the correct header and store any header not matching. So the function will first look in the cache and only look in the file if the entry is not found. This means that more then ten records might be stored, infact all barcode records that are not found in the read file will be kept as it currently is.

The reason that I only look into the next 10 barcode records is that I expect these missing read entries to be few. Should there be more than 10 missing read entries in a row this will fail but I assume these events to be rare. In the 1 million reads I had in the test 38 (or 0.0038%) barcode records missed corresponding read records. Therefore I think this is fine for now.

**Comment by marcelm** [comment]
Can you open a PR so we can discuss this next to the code?

**Comment by pontushojer** [comment]
Sure!

**Comment by FrickTobias** [comment]
I'll just test this before I close the issue.

**Comment by pontushojer** [comment]
![image](https://user-images.githubusercontent.com/27061883/68529301-8afc6680-02fd-11ea-878e-3fd0d85e7f08.png)

Memory profile for running tag_fastq on ~400 million reads on 20 cores on uppmax.

**Comment by FrickTobias** [comment]
Awesome! For future records I thought I'd include a reference from before.
![rackham-snic2018-3-501-tobiasf-10551985](https://user-images.githubusercontent.com/17293950/68544447-8ef2bc00-03c3-11ea-9256-6e1f0e074dfb.png)
