### ISSUE TITLE
SamToFastq fails because of unpaired mates

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#18]
When running the pipeline (on the test data), during the very last step when `SamToFastq` is used to convert the final BAM to FASTQ, the following error occurs:
```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Found 493 unpaired mates
```
I found a forum post by the author of Picard somewhere (sorry, lost the link) stating that this validation step occurs *after* the output FASTQ has already been written, which means that the error doesn’t become apparent unless one looks at the log file or checks the exit code.

The problem is that MarkDuplicates is run with `REMOVE_DUPLICATES=true`, which apparently deletes single reads out of pairs.

This can be “fixed” by adding `VALIDATION_STRINGENCY=silent` to SamToFastq, but that’s just hiding the problem. Usually, MarkDuplicates is indeed used to only mark duplicates, not to really remove them, in order to avoid losing data. The idea is that one can then (in theory) keep only a single BAM file and be able to reconstruct the full input FASTQ file from it. My preferred course of action would be to follow this best practice, but I don’t know how the created FASTQ and BAM files are actually used later.

**Comment by FrickTobias** [comment]
In an optimal solution, duplicates would not be removed here because of the problem you correctly point out with single reads out of pairs.

However, currently read duplicates are used for finding barcode duplicates (aka where two barcode has tagged the same molecule). This leads to two barcodes sharing a lot of proximal read duplicates which subsequently are merged into one barcode for all reads sharing that barcode sequence. 

The actual procedure doing this is first to remove all duplicates with the BARCODE_TAG=BC option and  afterwards analyze duplicate reads left in the file with cluster_rmdup.py (by first marking duplicates without the BARCODE_TAG flag).

I suggest that I rewrite the script to so it ignores duplicate reads at the same positions if they do not have different barcodes, essentially compacting the duplicate removal (BARCODE_TAG=BC), duplicate marking & cluster_rmdup step into duplicate removal & cluster_rmdup.
