### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#210]
I think we should include the current git commit hash in the version number to make it more easier to track which version of the pipe/tool that was used for a particular run. We should also include this in the run logs (snakemake log, blr.cli tools output) and BAM headers. 

@marcelm I saw that you have used `setuptools_scm` for this in `IgDiscover` and `cutadapt`. Could this be an good option?

**Comment by marcelm** [comment]
Yes, `setuptoools_scm` works really well! Whoever adds it: Don’t copy the configuration from IgDiscover or Cutadapt because the way to do it has changed recently. Also, use the `write_to` feature for generating a `_version.py` file (otherwise, version info is obtained via `pkg_resources`, and importing that is very slow).
