### ISSUE TITLE
Add all parameters to configs?

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#231]
# Discussion topic
1. Should we add all parameters to the configs or only a select subset?
2. If subset, what selects with parameters to include?
3. Difference between parameters for our tools (blr) vs external tools?

**Comment by marcelm** [comment]
I propose to keep it as simple as possible: Do not add anything to the configuration as long as it can be avoided. That is, wait for a user (which could be yourself) to request it, do not add it just because it "might be needed". Read about the [YAGNI principle](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) for a justification.
