### ISSUE TITLE
Include frameshift constructs

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#74]
We have started testing frameshift constructs for the BLR method. This means that the first handle might be preceded by 0, 1, 2 or 3 nucleotides. We should investigate how this affects the trimming and if we have to edit the trimming somehow to allow for this new setup.

**Comment by FrickTobias** [comment]
By just removing the anchoring we should reach similar results.

**Comment by marcelm** [comment]
Because just leaving out the anchoring gives you false positive matches in the middle of the read, I’ve added so-called [non-internal 5' adapters](https://cutadapt.readthedocs.io/en/stable/guide.html#non-internal-5-and-3-adapters) to Cutadapt a while ago. Instead of `-g ^HANDLE`, you would write `-g XNNNHANDLE` in this case. The `X` prevents the match from occurring in the middle of the read, but allows partial matches in the beginning. (And because of the three `N`s, up to three preceding nucleotides.) If you also set the minimum overlap length to the length of the handle, this will work as required.

**Comment by pontushojer** [comment]
This issue was resolved in PR #82.
