### ISSUE TITLE
Create a nice summary report

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#91]
After the pipeline has done all the computations, it should create a report. We can use MultiQC for this. It may be necessary to write our own plugin for it for the custom BLR-specific parts, but we can use its existing modules already now for Bowtie2, Cutadapt, MarkDuplicates etc.

**Comment by FrickTobias** [comment]
I've started working on adding some `fastqc` and `multiqc` steps to the pipe. However at this point of time I'm seeing this could be done in multiple ways which have different advantages.

1. Run `fastqc` before processing anything. This gives the user a way to check their data before running the pipe. 

2. Run `fastqc` after demultiplexing. This will require processing before running the qc but arguably a user could run an initial `fastqc` run on their raw reads if they want to. Regarding advantages this would make `fastqc` work a little better since it won't be confused by the handles. 

3. Run `fastqc` both before and after trimming. It doesn't take more processing power, the question is if this is interesting enough to include into the final output. Sometimes I think the mark of a really good program is also knowing when to not include output (provided it isn't relevant for normal usage).

Personally I'm more inclined to go for suggestion number two but I think this could be valuable to gather your input on.

**Comment by pontushojer** [comment]
I have started working on a MultiQC plugin to integrate our data to the MultiQC report. See [MultiQC_BLR](https://github.com/pontushojer/MultiQC_BLR).

**Comment by pontushojer** [comment]
https://github.com/NBISweden/BLR/pull/17 that integrates the BLR-plugin is now merged we have the basis for a summary report. Thus I will close this issue for now
